/* Generated By:JavaCC: Do not edit this line. ExpressionParserConstants.java */
package prefuse.data.expression.parser;

/** The Interface ExpressionParserConstants. */
public interface ExpressionParserConstants {
    /** The eof. */
    int EOF = 0;
    /** The true. */
    int TRUE = 6;
    /** The false. */
    int FALSE = 7;
    /** The null. */
    int NULL = 8;
    /** The if. */
    int IF = 9;
    /** The then. */
    int THEN = 10;
    /** The else. */
    int ELSE = 11;
    /** The and. */
    int AND = 12;
    /** The or. */
    int OR = 13;
    /** The not. */
    int NOT = 14;
    /** The xor. */
    int XOR = 15;
    /** The int. */
    int INT = 16;
    /** The decimal literal. */
    int DECIMAL_LITERAL = 17;
    /** The hex literal. */
    int HEX_LITERAL = 18;
    /** The octal literal. */
    int OCTAL_LITERAL = 19;
    /** The long. */
    int LONG = 20;
    /** The double. */
    int DOUBLE = 21;
    /** The float. */
    int FLOAT = 22;
    /** The exponent. */
    int EXPONENT = 23;
    /** The string. */
    int STRING = 24;
    /** The quoted. */
    int QUOTED = 25;
    /** The identifier. */
    int IDENTIFIER = 26;
    /** The letter. */
    int LETTER = 27;
    /** The digit. */
    int DIGIT = 28;
    /** The lparen. */
    int LPAREN = 29;
    /** The rparen. */
    int RPAREN = 30;
    /** The eq. */
    int EQ = 31;
    /** The gt. */
    int GT = 32;
    /** The lt. */
    int LT = 33;
    /** The le. */
    int LE = 34;
    /** The ge. */
    int GE = 35;
    /** The ne. */
    int NE = 36;
    /** The add. */
    int ADD = 37;
    /** The sub. */
    int SUB = 38;
    /** The mul. */
    int MUL = 39;
    /** The div. */
    int DIV = 40;
    /** The pow. */
    int POW = 41;
    /** The mod. */
    int MOD = 42;
    /** The default. */
    int DEFAULT = 0;
    /** The token image. */
    String[] tokenImage = { "<EOF>", "\" \"", "\"\\t\"", "\"\\n\"", "\"\\r\"", "\"\\f\"",
            "<TRUE>", "<FALSE>", "<NULL>", "<IF>", "<THEN>", "<ELSE>", "<AND>", "<OR>",
            "<NOT>", "<XOR>", "<INT>", "<DECIMAL_LITERAL>", "<HEX_LITERAL>",
            "<OCTAL_LITERAL>", "<LONG>", "<DOUBLE>", "<FLOAT>", "<EXPONENT>", "<STRING>",
            "<QUOTED>", "<IDENTIFIER>", "<LETTER>", "<DIGIT>", "\"(\"", "\")\"", "<EQ>",
            "\">\"", "\"<\"", "\"<=\"", "\">=\"", "<NE>", "\"+\"", "\"-\"", "\"*\"",
            "\"/\"", "\"^\"", "\"%\"", "\",\"", };
}
